### ISSUE TITLE
Make online server ⛷

### ISSUE THREAD

**Issue by TheAwiteb** [TheAwiteb/ticrs#3]
### Main Tasks
* [ ] Ask server for room
* [ ] Return board from server
* [ ] Register all rounds
* [ ] Playing with the round number
* [ ] Activate auto play (after 15s)
* [ ] Notify the player if he wants to play in a round that was played automatically
* [ ] Automatic play is random

### Subtasks
* [ ] Full documentation 📝
* [ ] Test all methods 🧪
